<a href="https://colab.research.google.com/github/aminrafi394/quera-AI-first-project/blob/Amirreza/Main_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
import pandas as pd

drive.mount("/content/drive")

data_frame_path = "/content/drive/MyDrive/Divar.csv"

data_frame = pd.read_csv(data_frame_path)

data_frame.head(10)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/tmp/ipykernel_36448/2932671274.py:8: DtypeWarning: Columns (11,27,29,53) have mixed types. Specify dtype option on import or set low_memory=False.
  data_frame = pd.read_csv(data_frame_path)

,Unnamed: 0,cat2_slug,cat3_slug,city_slug,neighborhood_slug,created_at_month,user_type,description,title,rent_mode,...,property_type,regular_person_capacity,extra_person_capacity,cost_per_extra_person,rent_price_on_regular_days,rent_price_on_special_days,rent_price_at_weekends,location_latitude,location_longitude,location_radius
0,0,temporary-rent,villa,karaj,mehrshahr,2024-08-01 00:00:00,مشاور املاک,۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...,باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه,NaN,...,NaN,4.0,6,350000.0,1500000.0,3.500000e+09,3500000.0,35.811684,50.936600,500.0
1,1,residential-sell,apartment-sell,tehran,gholhak,2024-05-01 00:00:00,مشاور املاک,دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...,۶۰ متر قلهک فول امکانات,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500.0
2,2,residential-rent,apartment-rent,tehran,tohid,2024-10-01 00:00:00,NaN,تخلیه پایان ماه,آپارتمان ۳ خوابه ۱۳۲ متر,مقطوع,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.703865,51.373459,NaN
3,3,commercial-rent,office-rent,tehran,elahiyeh,2024-06-01 00:00:00,NaN,فرشته تاپ لوکیشن\n۹۰ متر موقعیت اداری\nیک اتاق...,فرشته ۹۰ متر دفتر کار مدرن موقعیت اداری,مقطوع,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,residential-sell,apartment-sell,mashhad,emamreza,2024-05-01 00:00:00,مشاور املاک,هلدینگ ساختمانی اکبری\n\nهمراه شما هستیم برای ...,۱۱۵ متری/شمالی رو به آفتاب/اکبری,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,residential-rent,apartment-rent,ahvaz,mellirah,2024-09-01 00:00:00,NaN,اپارتمان ۱۰۰متری واحد جلو دارای دو اتاق خواب ک...,اپارتمان ۱۰۰متری ملی راه واحد جلو,مقطوع,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,commercial-rent,office-rent,kermanshah,NaN,2024-11-01 00:00:00,NaN,♦مشاورین املاک سیب♦\n✅️کد:G۱۰۵\n♦با سالها سابق...,واحداداری ۸۰متری ۲۲بهمن(برق),مقطوع,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,residential-sell,apartment-sell,tehran,dardasht,2024-09-01 00:00:00,مشاور املاک,♡♡♡♡♡♡بنام خدا♡♡♡♡♡♡\n♡♡♡عرض ادب واحترام♡♡♡\n♡...,اپارتمان ۱۰۰متری طبقه۳و۴ فول دردشت شمالی,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.729832,51.505466,500.0
8,8,residential-sell,apartment-sell,mahdasht-city,NaN,2024-06-01 00:00:00,مشاور املاک,با سلام\n\nاملاک بزرگ اتحاد با ۲شعبه فعال با ف...,۷۸متری دوبحرنورگیر بازسازی شده شیک سندتک برگ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.712364,50.794781,500.0
9,9,residential-sell,apartment-sell,mashhad,faramarzabbasi,2024-10-01 00:00:00,NaN,اول رسالت فرد نزدیک به حاشیه فرامرز .. ساکنین...,متراژ ۸۰ متر فرامرز نزدیک حاشیه,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

We make a copy of the main data frame.

In [3]:
cp_data_frame = data_frame.copy()
cp_data_frame["has_heating_system"].isna().sum()

#wwwwwwwwwwwwwwwwaaaaayyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

np.int64(631031)

First step is to get the houses with the price_value and remove the rent values.

In [4]:

cp_data_frame = cp_data_frame[cp_data_frame["price_value"].notna()].copy()

price_frame = np.log1p(cp_data_frame["price_value"].astype("float64"))
lower_bound, upper_bound = price_frame.quantile(0.05), price_frame.quantile(0.95)
mask = ((price_frame >= lower_bound) & (price_frame <= upper_bound)).to_numpy()
cp_data_frame = cp_data_frame[mask].copy()


cp_data_frame.head()

,Unnamed: 0,cat2_slug,cat3_slug,city_slug,neighborhood_slug,created_at_month,user_type,description,title,rent_mode,...,property_type,regular_person_capacity,extra_person_capacity,cost_per_extra_person,rent_price_on_regular_days,rent_price_on_special_days,rent_price_at_weekends,location_latitude,location_longitude,location_radius
1,1,residential-sell,apartment-sell,tehran,gholhak,2024-05-01 00:00:00,مشاور املاک,دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...,۶۰ متر قلهک فول امکانات,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500.0
4,4,residential-sell,apartment-sell,mashhad,emamreza,2024-05-01 00:00:00,مشاور املاک,هلدینگ ساختمانی اکبری\n\nهمراه شما هستیم برای ...,۱۱۵ متری/شمالی رو به آفتاب/اکبری,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,residential-sell,apartment-sell,tehran,dardasht,2024-09-01 00:00:00,مشاور املاک,♡♡♡♡♡♡بنام خدا♡♡♡♡♡♡\n♡♡♡عرض ادب واحترام♡♡♡\n♡...,اپارتمان ۱۰۰متری طبقه۳و۴ فول دردشت شمالی,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.729832,51.505466,500.0
8,8,residential-sell,apartment-sell,mahdasht-city,NaN,2024-06-01 00:00:00,مشاور املاک,با سلام\n\nاملاک بزرگ اتحاد با ۲شعبه فعال با ف...,۷۸متری دوبحرنورگیر بازسازی شده شیک سندتک برگ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.712364,50.794781,500.0
9,9,residential-sell,apartment-sell,mashhad,faramarzabbasi,2024-10-01 00:00:00,NaN,اول رسالت فرد نزدیک به حاشیه فرامرز .. ساکنین...,متراژ ۸۰ متر فرامرز نزدیک حاشیه,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

As we know the number of the lines with the Nan city_slug is less than 10 so we remove them.

In [5]:
cp_data_frame = cp_data_frame.dropna(subset=["city_slug"])
cp_data_frame["deed_type"].value_counts()

deed_type
single_page          179395
written_agreement     30225
other                 19253
multi_page             5741
unselect                523
Name: count, dtype: int64

In this part we want to get the effective feature and do some feature negineering.

In [6]:
cp_data_frame = cp_data_frame[["city_slug", "price_value", "land_size", "building_size", "rooms_count", "has_warehouse", "has_parking", "location_latitude"
  , "location_longitude", "cat2_slug", "cat3_slug", "construction_year","has_elevator", "has_balcony"
  ]]

In [7]:
!pip install arabic_reshaper
!pip install python-bidi

Requirement already satisfied: arabic_reshaper in /usr/local/lib/python3.13/dist-packages (3.0.1)
Requirement already satisfied: python-bidi in /usr/local/lib/python3.13/dist-packages (0.6.11)

In this part we split the train and the test data.

In [8]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(cp_data_frame, test_size=0.2, random_state=42)
train_data, validation_data = train_test_split(train_data, test_size=0.2, random_state=42)

As you can see the informations in the rooms_count are in the Persian language so we map the data into English.

In [9]:
from sklearn.preprocessing import FunctionTransformer

def room_count_persian(data_frame : pd.DataFrame) -> pd.DataFrame:
  map_rooms_count = {
    "دو" : 2,
    "یک" : 1,
    "سه" : 3,
    "بدون اتاق" : 0,
    "چهار" : 4,
    "پنج یا بیشتر" : 5
  }
  data_frame["rooms_count"] = data_frame["rooms_count"].map(map_rooms_count)
  return data_frame

room_count_transformer = FunctionTransformer(room_count_persian)
train_data = room_count_transformer.transform(train_data)
test_data = room_count_transformer.transform(test_data)
validation_data = room_count_transformer.transform(validation_data)


train_data.head()

,city_slug,price_value,land_size,building_size,rooms_count,has_warehouse,has_parking,location_latitude,location_longitude,cat2_slug,cat3_slug,construction_year,has_elevator,has_balcony
672026,ilam,6.500000e+09,NaN,250.0,3.0,True,True,33.641438,46.432758,residential-sell,apartment-sell,۱۴۰۳,True,NaN
84439,mashhad,8.000000e+09,326.0,190.0,2.0,True,True,NaN,NaN,residential-sell,house-villa-sell,۱۳۷۵,NaN,true
428932,firuzabad,8.500000e+08,NaN,95.0,2.0,True,True,28.831141,52.594612,residential-sell,apartment-sell,۱۳۹۴,True,NaN
783486,ahvaz,1.780000e+09,NaN,75.0,2.0,True,True,31.295769,48.718685,residential-sell,apartment-sell,۱۳۹۲,True,NaN
704347,tehran,7.200000e+09,NaN,102.0,2.0,True,True,NaN,NaN,residential-sell,apartment-sell,۱۴۰۳,True,NaN

In this part we want to user the construction part.

In [10]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import FunctionTransformer

class fill_constrution(BaseEstimator, TransformerMixin):
    def __init__(self, target_col: str = "construction_year", downcast: bool = True):
        self.target_col = target_col
        self.downcast = downcast
        self.cat3_medians_ = {}
        self.cat2_medians_ = {}
        self.city_medians_ = {}
        self.global_median_ = None

    def fit(self, X: pd.DataFrame, y=None):
        self.global_median_ = X[self.target_col].median()
        self.city_medians_ = X.groupby("city_slug")[self.target_col].median().to_dict()
        self.cat2_medians_ = X.groupby("cat2_slug")[self.target_col].median().to_dict()
        self.cat3_medians_ = X.groupby("cat3_slug")[self.target_col].median().to_dict()
        return self

    def transform(self, X: pd.DataFrame) -> pd.DataFrame:
        df = X.copy()

        imputed_cat3 = df["cat3_slug"].map(self.cat3_medians_)
        imputed_cat2 = df["cat2_slug"].map(self.cat2_medians_)
        imputed_city = df["city_slug"].map(self.city_medians_)

        df[self.target_col] = (
            df[self.target_col]
            .fillna(imputed_cat3)
            .fillna(imputed_cat2)
            .fillna(imputed_city)
            .fillna(self.global_median_)
        )

        if self.downcast:
            df[self.target_col] = df[self.target_col].round().astype("int16")

        return df

def clean_fa_digits(series: pd.Series) -> pd.Series:
    fa_digits = "۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩"
    en_digits = "01234567890123456789"
    trans_table = str.maketrans(fa_digits, en_digits)
    return series.astype(str).str.translate(trans_table)


def reshape_construction_year(df: pd.DataFrame) -> pd.DataFrame:
    data = df.copy()

    cleaned_col = clean_fa_digits(data["construction_year"])
    cleaned_col = cleaned_col.replace(
        {
            "قبل از 1370": "1369",
            "قبل از ۱۳۷۰": "1369",
        }
    )

    data["construction_year"] = pd.to_numeric(cleaned_col, errors="coerce")
    return data


reshaper = FunctionTransformer(reshape_construction_year)
train_data = reshaper.transform(train_data)
test_data = reshaper.transform(test_data)
validation_data = reshaper.transform(validation_data)


imputer = fill_constrution(target_col="construction_year", downcast=True)
train_data = imputer.fit_transform(train_data)
test_data = imputer.transform(test_data)
validation_data = imputer.transform(validation_data)


train_data["construction_year"]

672026    1403
84439     1375
428932    1394
783486    1392
704347    1403
          ...
595384    1403
819340    1369
196098    1396
934181    1396
871152    1385
Name: construction_year, Length: 327600, dtype: int16

In this part we ant to fill the Nan values fo the building size.
So, at first we group the houses based on teh city_slug
Then we fill it with the median of each city

In [11]:
from sklearn.base import BaseEstimator, TransformerMixin

class fill_building_size(BaseEstimator, TransformerMixin):
    def __init__(self, group_col: str = "city_slug", target_col: str = "building_size", downcast: bool = True):
        self.group_col = group_col
        self.target_col = target_col
        self.downcast = downcast
        self.group_medians_3 = {}
        self.group_medians_2 = {}
        self.group_medians_1 = {}
        self.global_median_ = None

    def fit(self, data_frame: pd.DataFrame, y=None):
        # calculating global median.
        self.global_median_ = data_frame[self.target_col].median()

        # calculating the median of each group based in the city_slug.
        self.group_medians_1 = (
            data_frame.groupby("city_slug")[self.target_col]
            .median()
            .to_dict()
        )
        self.group_medians_2 = (
            data_frame.groupby("cat2_slug")[self.target_col]
            .median()
            .to_dict()
        )
        self.group_medians_3 = (
            data_frame.groupby("cat3_slug")[self.target_col]
            .median()
            .to_dict()
        )
        return self

    def transform(self, data_frame, y=None):
        data_frame = data_frame.copy()
        missing_mask = data_frame[self.target_col].isna()

        if missing_mask.sum() == 0:
            return data_frame

        group_imputed_3 = data_frame["cat3_slug"].map(self.group_medians_3)
        group_imputed_2 = data_frame["cat2_slug"].map(self.group_medians_2)
        group_imputed_1 = data_frame["city_slug"].map(self.group_medians_1)

        imputed_value = (
            group_imputed_3
            .fillna(group_imputed_2)
            .fillna(group_imputed_1)
            .fillna(self.global_median_)
        )

        data_frame.loc[missing_mask, self.target_col] = imputed_value[missing_mask]
        return data_frame

building_imputer = fill_building_size(group_col="city_slug", target_col="building_size", downcast=True)

train_data = building_imputer.fit_transform(train_data)
test_data = building_imputer.transform(test_data)
validation_data = building_imputer.transform(validation_data)

In this part we fill the Nan values of the land_size with the median of eaech city (same as the building size) but we must be care full to remove the lines which the building size is bugger than the land size.

In [12]:
from sklearn.base import BaseEstimator, TransformerMixin

class fill_land_size(BaseEstimator, TransformerMixin):
    def __init__(self, group_col: str = "city_slug", target_col: str = "land_size", downcast: bool = True):
        self.group_col = group_col
        self.target_col = target_col
        self.downcast = downcast
        self.group_medians_3 = {}
        self.group_medians_2 = {}
        self.group_medians_1 = {}
        self.global_median_ = None

    def fit(self, data_frame: pd.DataFrame, y=None):
        # global median
        self.global_median_ = data_frame[self.target_col].median()

        # grouped median based on the city_slug.
        self.group_medians_3 = (
            data_frame.groupby("cat3_slug")[self.target_col]
            .median()
            .to_dict()
        )
        self.group_medians_2 = (
            data_frame.groupby("cat2_slug")[self.target_col]
            .median()
            .to_dict()
        )
        self.group_medians_1 = (
            data_frame.groupby("city_slug")[self.target_col]
            .median()
            .to_dict()
        )
        return self

    def transform(self, data_frame, y=None):
        data_frame = data_frame.copy()
        missing_mask = data_frame[self.target_col].isna()

        if missing_mask.sum() == 0:
            return data_frame

        group_imputed_3 = data_frame["cat3_slug"].map(self.group_medians_3)
        group_imputed_2 = data_frame["cat2_slug"].map(self.group_medians_2)
        group_imputed_1 = data_frame["city_slug"].map(self.group_medians_1)

        imputed_value = (
            group_imputed_3
            .fillna(group_imputed_2)
            .fillna(group_imputed_1)
            .fillna(self.global_median_)
        )

        data_frame.loc[missing_mask, self.target_col] = imputed_value[missing_mask]
        return data_frame

imputer = fill_land_size(group_col="city_slug", target_col="land_size", downcast=True)

train_data = imputer.fit_transform(train_data)
test_data = imputer.transform(test_data)
validation_data = imputer.transform(validation_data)

In this part we fil the Nan values based on the mode of the rooms_count grouped by city and building size.

In [13]:
def building_size_patintion(data_frame : pd.DataFrame):
    df = data_frame.copy()

    df.loc[df["building_size"] < 100, "building_size_level"] = "Low"
    df.loc[(df["building_size"] >= 100) & (df["building_size"] < 200), "building_size_level"] = "Medium"
    df.loc[df["building_size"] >= 200, "building_size_level"] = "High"

    return df

building_size_patintion = FunctionTransformer(building_size_patintion)
train_data = building_size_patintion.transform(train_data)
test_data = building_size_patintion.transform(test_data)
validation_data = building_size_patintion.transform(validation_data)


train_data.columns

Index(['city_slug', 'price_value', 'land_size', 'building_size', 'rooms_count',
       'has_warehouse', 'has_parking', 'location_latitude',
       'location_longitude', 'cat2_slug', 'cat3_slug', 'construction_year',
       'has_elevator', 'has_balcony', 'building_size_level'],
      dtype='object')

In [14]:
from sklearn.base import BaseEstimator, TransformerMixin

class fill_room_count(BaseEstimator, TransformerMixin):

    def __init__(self, target_col: str = "rooms_count", dtype: str = "int8"):
        self.target_col = target_col
        self.dtype = dtype
        self.group_mode_3 = {}
        self.group_mode_2 = {}
        self.group_mode_1 = {}
        self.global_median_ = None

    def _calc_mode(
        self, df: pd.DataFrame, group_cols: list[str]
    ) -> dict[tuple, float]:
        mode_series = (
            df.groupby(group_cols)[self.target_col]
            .agg(lambda s: s.mode().iloc[0] if not s.mode().empty else np.nan)
            .dropna()
        )
        return mode_series.to_dict()

    def fit(self, data_frame: pd.DataFrame, y=None):
        valid_mask = data_frame[self.target_col].notna()
        df_valid = data_frame.loc[valid_mask]

        self.group_mode_3 = self._calc_mode(
            df_valid, ["cat3_slug", "building_size_level"]
        )

        self.group_mode_2 = self._calc_mode(
            df_valid, ["cat2_slug", "building_size_level"]
        )

        self.group_mode_1 = self._calc_mode(
            df_valid, ["city_slug", "building_size_level"]
        )

        self.global_median_ = df_valid[self.target_col].median()

        return self

    def transform(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        data_frame = data_frame.copy()

        keys_3 = list(
            zip(data_frame["cat3_slug"], data_frame["building_size_level"])
        )
        mode_imputed_3 = pd.Series(keys_3, index=data_frame.index).map(
            self.group_mode_3
        )
        data_frame[self.target_col] = data_frame[self.target_col].fillna(
            mode_imputed_3
        )

        if data_frame[self.target_col].isna().any():
            keys_2 = list(
                zip(data_frame["cat2_slug"], data_frame["building_size_level"])
            )
            mode_imputed_2 = pd.Series(keys_2, index=data_frame.index).map(
                self.group_mode_2
            )
            data_frame[self.target_col] = data_frame[self.target_col].fillna(
                mode_imputed_2
            )

        if data_frame[self.target_col].isna().any():
            keys_1 = list(
                zip(data_frame["city_slug"], data_frame["building_size_level"])
            )
            mode_imputed_1 = pd.Series(keys_1, index=data_frame.index).map(
                self.group_mode_1
            )
            data_frame[self.target_col] = data_frame[self.target_col].fillna(
                mode_imputed_1
            )

        data_frame[self.target_col] = data_frame[self.target_col].fillna(
            self.global_median_
        )

        data_frame[self.target_col] = np.round(
            data_frame[self.target_col]
        ).astype(self.dtype)

        return data_frame

imputer = fill_room_count()
train_data = imputer.fit_transform(train_data)
test_data = imputer.transform(test_data)
validation_data = imputer.transform(validation_data)

In this part we want to full fill the has_elavator.

In [15]:
def normalize_bool_col(series: pd.Series) -> pd.Series:
    mapping = {
        True: 1, False: 0,
        'True': 1, 'False': 0,
        'true': 1, 'false': 0,
        '1': 1, '0': 0,
        1: 1, 0: 0,
    }
    return series.map(mapping)

In [16]:
from sklearn.base import BaseEstimator, TransformerMixin

class fill_elavator(BaseEstimator, TransformerMixin):

    def __init__(self, target_col: str = "has_elevator", dtype: str = "int8"):
        self.target_col = target_col
        self.dtype = dtype
        self.group_mode_3 = {}
        self.group_mode_2 = {}
        self.group_mode_1 = {}
        self.global_median_ = None

    def _calc_mode(
        self, df: pd.DataFrame, group_cols: list[str]
    ) -> dict[tuple, float]:
        mode_series = (
            df.groupby(group_cols)[self.target_col]
            .agg(lambda s: s.mode().iloc[0] if not s.mode().empty else np.nan)
            .dropna()
        )
        return mode_series.to_dict()

    def fit(self, data_frame: pd.DataFrame, y=None):
        valid_mask = data_frame[self.target_col].notna()
        df_valid = data_frame.loc[valid_mask]

        self.group_mode_3 = self._calc_mode(
            df_valid, ["cat3_slug", "building_size_level"]
        )

        self.group_mode_2 = self._calc_mode(
            df_valid, ["cat2_slug", "building_size_level"]
        )

        self.group_mode_1 = self._calc_mode(
            df_valid, ["city_slug", "building_size_level"]
        )

        self.global_median_ = df_valid[self.target_col].median()

        return self

    def transform(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        data_frame = data_frame.copy()

        keys_3 = list(
            zip(data_frame["cat3_slug"], data_frame["building_size_level"])
        )
        mode_imputed_3 = pd.Series(keys_3, index=data_frame.index).map(
            self.group_mode_3
        )
        data_frame[self.target_col] = data_frame[self.target_col].fillna(
            mode_imputed_3
        )

        if data_frame[self.target_col].isna().any():
            keys_2 = list(
                zip(data_frame["cat2_slug"], data_frame["building_size_level"])
            )
            mode_imputed_2 = pd.Series(keys_2, index=data_frame.index).map(
                self.group_mode_2
            )
            data_frame[self.target_col] = data_frame[self.target_col].fillna(
                mode_imputed_2
            )

        if data_frame[self.target_col].isna().any():
            keys_1 = list(
                zip(data_frame["city_slug"], data_frame["building_size_level"])
            )
            mode_imputed_1 = pd.Series(keys_1, index=data_frame.index).map(
                self.group_mode_1
            )
            data_frame[self.target_col] = data_frame[self.target_col].fillna(
                mode_imputed_1
            )

        data_frame[self.target_col] = data_frame[self.target_col].fillna(
            self.global_median_
        )

        data_frame[self.target_col] = np.round(
            data_frame[self.target_col]
        ).astype(self.dtype)

        return data_frame

train_data['has_elevator'] = normalize_bool_col(train_data['has_elevator'])
test_data['has_elevator'] = normalize_bool_col(test_data['has_elevator'])
validation_data['has_elevator'] = normalize_bool_col(validation_data['has_elevator'])



imputer = fill_elavator()
train_data = imputer.fit_transform(train_data)
test_data = imputer.transform(test_data)
validation_data = imputer.transform(validation_data)

In thi part we want to fill the has_balcony

In [17]:
from sklearn.base import BaseEstimator, TransformerMixin


class fill_balcany(BaseEstimator, TransformerMixin):

    def __init__(self, target_col: str = "has_balcony", dtype: str = "int8"):
        self.target_col = target_col
        self.dtype = dtype
        self.group_mode_3 = {}
        self.group_mode_2 = {}
        self.group_mode_1 = {}
        self.global_median_ = None

    def _calc_mode(
        self, df: pd.DataFrame, group_cols: list[str]
    ) -> dict[tuple, float]:
        mode_series = (
            df.groupby(group_cols)[self.target_col]
            .agg(lambda s: s.mode().iloc[0] if not s.mode().empty else np.nan)
            .dropna()
        )
        return mode_series.to_dict()

    def fit(self, data_frame: pd.DataFrame, y=None):
        df = data_frame.copy()
        df[self.target_col] = normalize_bool_col(df[self.target_col])

        target_series = df[self.target_col]

        valid_mask = target_series.notna()
        df_valid = df.loc[valid_mask].copy()

        self.group_mode_3 = self._calc_mode(
            df_valid, ["cat3_slug", "building_size_level"]
        )
        self.group_mode_2 = self._calc_mode(
            df_valid, ["cat2_slug", "building_size_level"]
        )
        self.group_mode_1 = self._calc_mode(
            df_valid, ["city_slug", "building_size_level"]
        )

        self.global_median_ = df_valid[self.target_col].median()

        return self


    def transform(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        data_frame = data_frame.copy()

        data_frame[self.target_col] = pd.to_numeric(
            data_frame[self.target_col], errors="coerce"
        )

        index_3 = pd.MultiIndex.from_arrays(
            [data_frame["cat3_slug"], data_frame["building_size_level"]]
        )
        data_frame[self.target_col] = data_frame[self.target_col].fillna(
            pd.Series(index_3.map(self.group_mode_3), index=data_frame.index)
        )

        if data_frame[self.target_col].isna().any():
            index_2 = pd.MultiIndex.from_arrays(
                [data_frame["cat2_slug"], data_frame["building_size_level"]]
            )
            data_frame[self.target_col] = data_frame[self.target_col].fillna(
                pd.Series(
                    index_2.map(self.group_mode_2), index=data_frame.index
                )
            )

        if data_frame[self.target_col].isna().any():
            index_1 = pd.MultiIndex.from_arrays(
                [data_frame["city_slug"], data_frame["building_size_level"]]
            )
            data_frame[self.target_col] = data_frame[self.target_col].fillna(
                pd.Series(
                    index_1.map(self.group_mode_1), index=data_frame.index
                )
            )

        data_frame[self.target_col] = data_frame[self.target_col].fillna(
            self.global_median_
        )

        data_frame[self.target_col] = np.round(
            data_frame[self.target_col]
        ).astype(self.dtype)

        return data_frame

imputer = fill_balcany()
train_data = imputer.fit_transform(train_data)
test_data = imputer.transform(test_data)
validation_data = imputer.transform(validation_data)

In this part we want to fill the has_parking.

In [18]:
from sklearn.base import BaseEstimator, TransformerMixin

parking_map = {
    True: 1, False: 0,
    "True": 1, "False": 0,
    "true": 1, "false": 0,
    1: 1, 0: 0,
    "1": 1, "0": 0
}
train_data["has_parking"] = train_data["has_parking"].map(parking_map)
test_data["has_parking"] = test_data["has_parking"].map(parking_map)


class fill_has_parking(BaseEstimator, TransformerMixin):

    def __init__(self, target_col: str = "has_parking"):
        self.target_col = target_col
        self.group_modes_3 = {}
        self.group_modes_2 = {}
        self.group_modes_1 = {}
        self.global_mode_ = None

    @staticmethod
    def _calc_mode(series: pd.Series):
        m = series.mode()
        return m.iloc[0] if not m.empty else np.nan

    def fit(self, data_frame: pd.DataFrame, y=None):

        m = data_frame[self.target_col].mode()
        self.global_mode_ = m.iloc[0] if not m.empty else np.nan

        self.group_modes_3 = (
            data_frame.groupby("cat3_slug")[self.target_col]
            .agg(self._calc_mode)
            .to_dict()
        )
        self.group_modes_2 = (
            data_frame.groupby("cat2_slug")[self.target_col]
            .agg(self._calc_mode)
            .to_dict()
        )
        self.group_modes_1 = (
            data_frame.groupby("city_slug")[self.target_col]
            .agg(self._calc_mode)
            .to_dict()
        )
        return self

    def transform(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        data_frame = data_frame.copy()

        group_imputed_3 = data_frame["cat3_slug"].map(self.group_modes_3)
        group_imputed_2 = data_frame["cat2_slug"].map(self.group_modes_2)
        group_imputed_1 = data_frame["city_slug"].map(self.group_modes_1)

        data_frame[self.target_col] = (
            data_frame[self.target_col]
            .fillna(group_imputed_3)
            .fillna(group_imputed_2)
            .fillna(group_imputed_1)
            .fillna(self.global_mode_)
        )

        return data_frame



imputer = fill_has_parking(target_col="has_parking")

train_data = imputer.fit_transform(train_data)
test_data = imputer.transform(test_data)
validation_data = imputer.transform(validation_data)


print(train_data["has_parking"].value_counts(dropna=False))

has_parking
1.0    280016
0.0     47584
Name: count, dtype: int64

In this part we want to full fill the has_warehouse part.
The mian logic is that if th ehouse had a parking orwarehouse the seller would say it to incearse the house price if it is Nan or missed it means the it should be filled with  0.

In [19]:
class fill_cordinate(BaseEstimator, TransformerMixin):
    def __init__(
        self,
        target_col: str,
        city_col: str = "city_slug",
        dtype: str = "float64"
    ):
        self.target_col = target_col
        self.city_col = city_col
        self.dtype = dtype

        self.city_median_ = {}
        self.global_median_ = None

    def fit(self, data_frame: pd.DataFrame, y=None):
        valid_mask = data_frame[self.target_col].notna()
        df_valid = data_frame.loc[valid_mask]


        # calculating the medain based on the city.
        self.city_median_ = (
            df_valid.groupby(self.city_col)[self.target_col]
            .median()
            .dropna()
            .to_dict()
        )

        # global median.
        self.global_median_ = df_valid[self.target_col].median()

        return self

    def transform(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        data_frame = data_frame.copy()

        # based on the city.
        imputed_l2 = data_frame[self.city_col].map(self.city_median_)
        data_frame[self.target_col] = data_frame[self.target_col].fillna(imputed_l2)

        # global median.
        data_frame[self.target_col] = data_frame[self.target_col].fillna(self.global_median_)

        # Casting
        data_frame[self.target_col] = data_frame[self.target_col].astype(self.dtype)

        return data_frame


lat_imputer = fill_cordinate(
    target_col="location_latitude",
    city_col="city_slug",
    dtype="float64"
)

lon_imputer = fill_cordinate(
    target_col="location_longitude",
    city_col="city_slug",
    dtype="float64"
)

train_data = lat_imputer.fit_transform(train_data)
train_data = lon_imputer.fit_transform(train_data)

validation_data = lat_imputer.transform(validation_data)
validation_data = lon_imputer.transform(validation_data)

test_data = lat_imputer.transform(test_data)
test_data = lon_imputer.transform(test_data)

In this part we want to has_warehouse.

In [20]:
from sklearn.base import BaseEstimator, TransformerMixin

train_data['has_warehouse'] = normalize_bool_col(train_data['has_warehouse'])
test_data['has_warehouse'] = normalize_bool_col(test_data['has_warehouse'])


class fill_has_warehouse(BaseEstimator, TransformerMixin):

    def __init__(self, target_col: str = "has_warehouse"):
        self.target_col = target_col
        self.group_modes_3 = {}
        self.group_modes_2 = {}
        self.group_modes_1 = {}
        self.global_mode_ = None

    @staticmethod
    def _calc_mode(series: pd.Series):
        m = series.mode()
        return m.iloc[0] if not m.empty else np.nan

    def fit(self, data_frame: pd.DataFrame, y=None):

        m = data_frame[self.target_col].mode()
        self.global_mode_ = m.iloc[0] if not m.empty else np.nan

        self.group_modes_3 = (
            data_frame.groupby("cat3_slug")[self.target_col]
            .agg(self._calc_mode)
            .to_dict()
        )
        self.group_modes_2 = (
            data_frame.groupby("cat2_slug")[self.target_col]
            .agg(self._calc_mode)
            .to_dict()
        )
        self.group_modes_1 = (
            data_frame.groupby("city_slug")[self.target_col]
            .agg(self._calc_mode)
            .to_dict()
        )
        return self

    def transform(self, data_frame: pd.DataFrame) -> pd.DataFrame:
        data_frame = data_frame.copy()

        group_imputed_3 = data_frame["cat3_slug"].map(self.group_modes_3)
        group_imputed_2 = data_frame["cat2_slug"].map(self.group_modes_2)
        group_imputed_1 = data_frame["city_slug"].map(self.group_modes_1)

        data_frame[self.target_col] = (
            data_frame[self.target_col]
            .fillna(group_imputed_3)
            .fillna(group_imputed_2)
            .fillna(group_imputed_1)
            .fillna(self.global_mode_)
        )

        return data_frame


imputer = fill_has_warehouse(target_col="has_warehouse")

train_data = imputer.fit_transform(train_data)
test_data = imputer.transform(test_data)
validation_data = imputer.transform(validation_data)


print(train_data["has_warehouse"].value_counts(dropna=False))

has_warehouse
1.0    289010
0.0     38590
Name: count, dtype: int64

Some feature adding.

In this part we remove the unnccery feature like city_slug and building_size_level and remove the Nan values of the price_value.

In [21]:
cat_cols = ["city_slug", "cat2_slug", "cat3_slug"]

categories = {
    c: pd.Index(train_data[c].dropna().unique())
    for c in cat_cols
}

for c in cat_cols:
    train_data[c] = pd.Categorical(train_data[c], categories=categories[c])
    test_data[c]  = pd.Categorical(test_data[c],  categories=categories[c])

level_map = {"Low": 0, "Medium": 1, "High": 2}
train_data["building_size_level"] = (
    train_data["building_size_level"].map(level_map).astype("UInt8")
)
test_data["building_size_level"] = (
    test_data["building_size_level"].map(level_map).astype("UInt8")
)

train_data = train_data.dropna(subset=["price_value"])
test_data = test_data.dropna(subset=["price_value"])

train_x = train_data.drop(columns=["price_value"])
test_x = test_data.drop(columns=["price_value"])
val_x = validation_data.drop(columns=["price_value"])

train_y = train_data["price_value"]
test_y = test_data["price_value"]
val_y = validation_data["price_value"]

Adding some feature.

In [22]:
city_lat_center = train_x.groupby('city_slug')['location_latitude'].median()
city_lon_center = train_x.groupby('city_slug')['location_longitude'].median()


def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371.0
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    return R * 2 * np.arcsin(np.sqrt(a))


def add_features(df, city_lat_center, city_lon_center):
    df = df.copy()

    df['building_land_ratio'] = df['building_size'] / (df['land_size'] + 1)

    df['area_per_room'] = df['building_size'] / df['rooms_count'].replace(0, 1)

    center_lat = df['city_slug'].map(city_lat_center).astype(float)
    center_lon = df['city_slug'].map(city_lon_center).astype(float)
    lat = df['location_latitude'].astype(float).values
    lon = df['location_longitude'].astype(float).values
    df['dist_to_city_center'] = haversine_distance(
        df['location_latitude'].values,
        df['location_longitude'].values,
        center_lat.values,
        center_lon.values,
    )

    df['building_age'] = (1403 - df['construction_year']).clip(0, 100)

    df['size_age_interact'] = df['building_size'] / (df['building_age'] + 1)

    new_cols = [
        'building_land_ratio',
        'area_per_room',
        'dist_to_city_center',
        'building_age',
        'size_age_interact',
    ]
    for col in new_cols:
        df[col] = df[col].fillna(df[col].median())

    return df

train_x = add_features(train_x, city_lat_center, city_lon_center)
val_x = add_features(val_x,   city_lat_center, city_lon_center)
test_x = add_features(test_x,   city_lat_center, city_lon_center)

/tmp/ipykernel_36448/520259556.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  city_lat_center = train_x.groupby('city_slug')['location_latitude'].median()
/tmp/ipykernel_36448/520259556.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  city_lon_center = train_x.groupby('city_slug')['location_longitude'].median()

give a code to each category in the data frame.

In [23]:
!pip install category-encoders

Requirement already satisfied: category-encoders in /usr/local/lib/python3.13/dist-packages (2.11.1)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.13/dist-packages (from category-encoders) (2.1.3)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.13/dist-packages (from category-encoders) (2.2.3)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from category-encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from category-encoders) (1.16.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.5->category-encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.5->category-encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.0.5->category-encoders) (2026.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.6.0->category-encoders) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.6.0->category-encoders) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=1.6.0->category-encoders) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category-encoders) (1.17.0)

In [24]:
from category_encoders import TargetEncoder

encoder = TargetEncoder(cols=['city_slug','cat2_slug','cat3_slug'], smoothing=10)
train_x = encoder.fit_transform(train_x, train_y)
val_x   = encoder.transform(val_x)
test_x   = encoder.transform(test_x)

In this case we use a simple xgboost to test our preproccessing.

In [25]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (3.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.31.2)

In [26]:
parking_map = {
    True: 1, 'True': 1, '1': 1, 1: 1,
    False: 0, 'False': 0, '0': 0, 0: 0
}
val_x['has_parking'] = val_x['has_parking'].map(parking_map).fillna(0).astype('int8')
test_x['has_parking'] = test_x['has_parking'].map(parking_map).fillna(0).astype('int8')

def normalize_bool_col(series):
    mapping = {True: 1, 'True': 1, '1': 1, 1: 1,
               False: 0, 'False': 0, '0': 0, 0: 0}
    return series.map(mapping).fillna(0).astype('int8')

train_x['has_warehouse'] = normalize_bool_col(train_x['has_warehouse'])
val_x['has_warehouse']   = normalize_bool_col(val_x['has_warehouse'])
test_x['has_warehouse']  = normalize_bool_col(test_x['has_warehouse'])

size_level_map = {'Low': 0, 'Medium': 1, 'High': 2}
for df in [train_x, val_x, test_x]:
    if 'building_size_level' in df.columns:
        df['building_size_level'] = df['building_size_level'].map(size_level_map).fillna(0).astype('int8')

object_cols = train_x.select_dtypes(include='object').columns.tolist()
if object_cols:
    print("Still object dtype:", object_cols)
else:
    print("All dtypes OK — ready for XGBoost")

All dtypes OK — ready for XGBoost

In [27]:
from sklearn.metrics import mean_absolute_error, r2_score
from xgboost import XGBRegressor
import numpy as np

train_y = np.log1p(train_y)
test_y  = np.log1p(test_y)
val_y   = np.log1p(val_y)

model = XGBRegressor(
    n_estimators=2000,
    learning_rate=0.03,
    max_depth=5,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.7,
    colsample_bylevel=0.7,
    reg_alpha=0.1,
    reg_lambda=1.0,
    gamma=0.1,
    random_state=42,
    tree_method='hist',
    early_stopping_rounds=100,
    eval_metric='rmse',
    n_jobs=-1,
    enable_categorical=True,
)

model.fit(
    train_x, train_y,
    eval_set=[(val_x, val_y)],
    verbose=200
)

y_pred_log = model.predict(val_x)
y_pred = np.expm1(y_pred_log)

val_y = np.expm1(val_y)
train_y = np.expm1(train_y)
test_y = np.expm1(test_y)

print(f"MAE    : {mean_absolute_error(val_y, y_pred):,.0f}")
print(f"R2     : {r2_score(val_y, y_pred):.4f}")

train_pred = np.expm1(model.predict(train_x))
print(f"Train R2: {r2_score(train_y, train_pred):.4f}")

test_pred = np.expm1(model.predict(test_x))
print(f"MAE Test    : {mean_absolute_error(test_y, test_pred):,.0f}")
print(f"R2 Test     : {r2_score(test_y, test_pred):.4f}")

[0]	validation_0-rmse:0.89238
[200]	validation_0-rmse:0.58391
[400]	validation_0-rmse:0.56844
[600]	validation_0-rmse:0.56009
[800]	validation_0-rmse:0.55404
[1000]	validation_0-rmse:0.54945
[1200]	validation_0-rmse:0.54628
[1400]	validation_0-rmse:0.54375
[1600]	validation_0-rmse:0.54166
[1800]	validation_0-rmse:0.53991
[1999]	validation_0-rmse:0.53837
MAE    : 1,351,944,491
R2     : 0.6099
Train R2: 0.6254
MAE Test    : 1,350,876,128
R2 Test     : 0.6083