# Divar Real Estate Analysis — Descriptive Statistics

**Questions:**
- **Q8:** Correlation Matrix of Price, Size, Capacity, Rooms and Location
- **Q9:** Regional Distribution of Properties with Balcony, Elevator, Security Guard, Barbecue and Pool

**Author:** Mahdi Tarrah

**Data:** `data/Divar.csv`

In [1]:
import pandas as pd

In [2]:
#cheak 1000 narrow
df_cheak = pd.read_csv('../data/Divar.csv', nrows=1000)

In [3]:
#cheak datatypes of each columns
df_cheak.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 61 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  1000 non-null   int64
 1   cat2_slug                   1000 non-null   str
 2   cat3_slug                   1000 non-null   str
 3   city_slug                   1000 non-null   str
 4   neighborhood_slug           438 non-null    str
 5   created_at_month            1000 non-null   str
 6   user_type                   288 non-null    str
 7   description                 1000 non-null   str
 8   title                       1000 non-null   str
 9   rent_mode                   330 non-null    str
 10  rent_value                  328 non-null    float64
 11  rent_to_single              0 non-null      float64
 12  rent_type                   101 non-null    str
 13  price_mode                  599 non-null    str
 14  price_value                 590 non-null    float64
 15  credit_mode                 330 non-null    str
 16  credit_value                329 non-null    float64
 17  rent_credit_transform       330 non-null    object
 18  transformable_price         330 non-null    object
 19  transformable_credit        329 non-null    float64
 20  transformed_credit          61 non-null     float64
 21  transformable_rent          328 non-null    float64
 22  transformed_rent            61 non-null     float64
 23  land_size                   171 non-null    float64
 24  building_size               988 non-null    float64
 25  deed_type                   235 non-null    str
 26  has_business_deed           39 non-null     object
 27  floor                       546 non-null    float64
 28  rooms_count                 836 non-null    str
 29  total_floors_count          284 non-null    float64
 30  unit_per_floor              280 non-null    str
 31  has_balcony                 473 non-null    object
 32  has_elevator                546 non-null    object
 33  has_warehouse               717 non-null    object
 34  has_parking                 717 non-null    object
 35  construction_year           800 non-null    str
 36  is_rebuilt                  506 non-null    object
 37  has_water                   30 non-null     object
 38  has_warm_water_provider     350 non-null    str
 39  has_electricity             30 non-null     object
 40  has_gas                     30 non-null     object
 41  has_heating_system          336 non-null    str
 42  has_cooling_system          315 non-null    str
 43  has_restroom                378 non-null    str
 44  has_security_guard          28 non-null     object
 45  has_barbecue                27 non-null     object
 46  building_direction          307 non-null    str
 47  has_pool                    27 non-null     object
 48  has_jacuzzi                 27 non-null     object
 49  has_sauna                   27 non-null     object
 50  floor_material              372 non-null    str
 51  property_type               32 non-null     str
 52  regular_person_capacity     36 non-null     float64
 53  extra_person_capacity       34 non-null     float64
 54  cost_per_extra_person       14 non-null     float64
 55  rent_price_on_regular_days  25 non-null     float64
 56  rent_price_on_special_days  13 non-null     float64
 57  rent_price_at_weekends      16 non-null     float64
 58  location_latitude           645 non-null    float64
 59  location_longitude          645 non-null    float64
 60  location_radius             340 non-null    float64
dtypes: float64(21), int64(1), object(16), str(23)
memory usage: 476.7+ KB

In [4]:
#see data
df_cheak.head()

,Unnamed: 0,cat2_slug,cat3_slug,city_slug,neighborhood_slug,created_at_month,user_type,description,title,rent_mode,...,property_type,regular_person_capacity,extra_person_capacity,cost_per_extra_person,rent_price_on_regular_days,rent_price_on_special_days,rent_price_at_weekends,location_latitude,location_longitude,location_radius
0,0,temporary-rent,villa,karaj,mehrshahr,2024-08-01 00:00:00,مشاور املاک,۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...,باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه,NaN,...,NaN,4.0,6.0,350000.0,1500000.0,3.500000e+09,3500000.0,35.811684,50.936600,500.0
1,1,residential-sell,apartment-sell,tehran,gholhak,2024-05-01 00:00:00,مشاور املاک,دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...,۶۰ متر قلهک فول امکانات,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500.0
2,2,residential-rent,apartment-rent,tehran,tohid,2024-10-01 00:00:00,NaN,تخلیه پایان ماه,آپارتمان ۳ خوابه ۱۳۲ متر,مقطوع,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.703865,51.373459,NaN
3,3,commercial-rent,office-rent,tehran,elahiyeh,2024-06-01 00:00:00,NaN,فرشته تاپ لوکیشن\n۹۰ متر موقعیت اداری\nیک اتاق...,فرشته ۹۰ متر دفتر کار مدرن موقعیت اداری,مقطوع,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,residential-sell,apartment-sell,mashhad,emamreza,2024-05-01 00:00:00,مشاور املاک,هلدینگ ساختمانی اکبری\n\nهمراه شما هستیم برای ...,۱۱۵ متری/شمالی رو به آفتاب/اکبری,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#read all columns we need for Q8
q8_columns = ['price_value','land_size','building_size','regular_person_capacity','rooms_count','location_latitude','location_longitude','city_slug','cat3_slug']
df_q8 = pd.read_csv('../data/Divar.csv', usecols=q8_columns)
df_q8.shape

(1000000, 9)

In [6]:
#cheak_nulls
df_q8.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 9 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   cat3_slug                999999 non-null  str
 1   city_slug                999998 non-null  str
 2   price_value              568346 non-null  float64
 3   land_size                186396 non-null  float64
 4   building_size            980394 non-null  float64
 5   rooms_count              845899 non-null  str
 6   regular_person_capacity  29870 non-null   float64
 7   location_latitude        655608 non-null  float64
 8   location_longitude       655608 non-null  float64
dtypes: float64(6), str(3)
memory usage: 68.7 MB

In [7]:
#cheak for impossible value
df_q8.describe().T

,count,mean,std,min,25%,50%,75%,max
price_value,568346.0,1.736537e+10,5.878739e+11,0.000000,1.400000e+09,2.840000e+09,5.900000e+09,1.000000e+14
land_size,186396.0,4.165480e+03,1.218927e+05,1.000000,1.100000e+02,1.950000e+02,2.800000e+02,1.000000e+07
building_size,980394.0,4.440648e+03,1.367118e+05,1.000000,7.500000e+01,1.030000e+02,1.650000e+02,1.000000e+07
regular_person_capacity,29870.0,6.557650e+00,7.698655e+00,1.000000,3.000000e+00,4.000000e+00,7.000000e+00,5.000000e+01
location_latitude,655608.0,3.498211e+01,2.379169e+00,23.626478,3.455355e+01,3.572331e+01,3.630701e+01,4.035806e+01
location_longitude,655608.0,5.162974e+01,3.160920e+00,40.162369,5.067717e+01,5.134579e+01,5.180529e+01,7.451162e+01

In [8]:
#cheak values of rooms_count
df_q8['rooms_count'].value_counts(dropna=False)

rooms_count
دو              404050
یک              192083
NaN             154101
سه              138633
بدون اتاق        75898
چهار             21371
پنج یا بیشتر     13864
Name: count, dtype: int64